const SCHEMA_PROPS = {
    Article: ["headline", "image", "datePublished", "dateModified", "author", "publisher"],
    BlogPosting: ["headline", "image", "datePublished", "dateModified", "author", "publisher"],
    BreadcrumbList: ["itemListElement"],
    ClaimReview: ["claimReviewed", "reviewRating", "author", "datePublished", "itemReviewed"],
    Course: ["name", "description", "provider"],
    Dataset: ["name", "description", "creator", "license", "distribution"],
    EmployerAggregateRating: ["itemReviewed", "ratingValue", "ratingCount"],
    Event: ["name", "startDate", "endDate", "location", "image", "description", "offers", "performer", "organizer", "eventStatus"],
    FAQPage: ["mainEntity"],
    HowTo: ["name", "description", "step", "image", "estimatedCost", "totalTime", "supply", "tool"],
    ImageObject: ["contentUrl", "creator", "creditText", "copyrightNotice", "license", "acquireLicensePage"],
    JobPosting: ["title", "description", "datePosted", "validThrough", "employmentType", "hiringOrganization", "jobLocation", "baseSalary"],
    LocalBusiness: ["name", "image", "@id", "url", "telephone", "address", "geo", "openingHoursSpecification", "priceRange", "department"],
    Movie: ["name", "image", "dateCreated", "director", "actor"],
    NewsArticle: ["headline", "image", "datePublished", "dateModified", "author", "publisher"],
    Organization: ["name", "url", "logo", "sameAs", "contactPoint"],
    Person: ["name", "url", "image", "jobTitle", "worksFor", "sameAs"],
    Product: ["name", "image", "description", "brand", "sku", "gtin", "gtin8", "gtin12", "gtin13", "gtin14", "offers", "aggregateRating", "review"],
    ProfilePage: ["mainEntity"],
    QAPage: ["mainEntity"],
    Recipe: ["name", "image", "author", "datePublished", "description", "prepTime", "cookTime", "totalTime", "recipeYield", "recipeCategory", "recipeCuisine", "nutrition", "recipeIngredient", "recipeInstructions", "video"],
    Review: ["itemReviewed", "author", "reviewRating", "datePublished", "reviewBody", "publisher"],
    SoftwareApplication: ["name", "operatingSystem", "applicationCategory", "aggregateRating", "offers"],
    VideoObject: ["name", "description", "thumbnailUrl", "uploadDate", "contentUrl", "embedUrl", "duration", "interactionStatistic", "regionsAllowed"],
    WebSite: ["name", "url", "potentialAction"]
};
